---
name: bosh

releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=168
    sha1: 57320a93a7a15e51af4c57d9d9c22706c45c9953
  - name: bosh-google-cpi
    url: http://storage.googleapis.com/bosh-stemcells/bosh-google-cpi-5.tgz
    sha1: c5de3053f233e6ef42c2a4228fa94179d955cc84

resource_pools:
  - name: vms
    network: private
    stemcell:
      url: http://storage.googleapis.com/bosh-stemcells/light-bosh-stemcell-2968-google-kvm-ubuntu-trusty-go_agent.tgz
      sha1: ce5a64c3ecef4fd3e6bd633260dfaa7de76540eb
    cloud_properties:
      machine_type: n1-standard-2
      root_disk_size_gb: 40
      root_disk_type: pd-standard

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: private
    type: dynamic
    cloud_properties:
      network_name: default
      tags:
        - bosh

  - name: public
    type: vip

jobs:
  - name: bosh
    instances: 1

    templates:
      - name: nats
        release: bosh
      - name: redis
        release: bosh
      - name: postgres
        release: bosh
      - name: powerdns
        release: bosh
      - name: blobstore
        release: bosh
      - name: director
        release: bosh
      - name: health_monitor
        release: bosh
      - name: cpi
        release: bosh-google-cpi
      - name: registry
        release: bosh-google-cpi

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        default:
          - dns
          - gateway
      - name: public
        static_ips:
          - 104.197.123.230 # <--- Replace with the static IP

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: nats

      redis:
        listen_address: 127.0.0.1
        address: 127.0.0.1
        password: redis

      postgres: &db
        adapter: postgres
        host: 127.0.0.1
        user: postgres
        password: postgres
        database: bosh

      dns:
        address: 104.197.123.230 # <--- Replace with the static IP
        domain_name: microbosh
        db: *db
        recursor: 8.8.8.8

      blobstore:
        address: 104.197.123.230 # <--- Replace with the static IP
        provider: dav
        director:
          user: director
          password: director
        agent:
          user: agent
          password: agent

      director:
        address: 127.0.0.1
        name: micro-google
        db: *db
        cpi_job: cpi

      hm:
        http:
          user: hm
          password: hm
        director_account:
          user: admin
          password: admin
        resurrector_enabled: true

      ntp: &ntp
        - 169.254.169.254

      google: &google_properties
        project: connectedearthsciences	 # <--- Replace with your GCE project
        json_key: "" # <--- Replace with your GCE JSON key
        default_zone: us-central1-a # <--- Replace with the GCE zone to use by default

      agent:
        mbus: nats://nats:nats@104.197.123.230:4222 # <--- Replace with the static IP
        ntp: *ntp
        blobstore:
           options:
             endpoint: http://104.197.123.230:25250 # <--- Replace with the static IP
             user: agent
             password: agent

      registry:
        host: 104.197.123.230 # <--- Replace with the static IP
        username: registry
        password: registry

cloud_provider:
  template:
    name: cpi
    release: bosh-google-cpi

  ssh_tunnel:
    host: 104.197.123.230 # <--- Replace with the static IP
    port: 22
    user: christopher # <--- Replace with the user corresponding to your private SSH key
    private_key: /bosh-workspace/keys/connectedearthsciences-45616b2f61ce.p12 # <--- Replace with the location of your google_compute_engine SSH private key

  mbus: https://mbus:mbus@104.197.123.230:6868 # <--- Replace with the static IP

  properties:
    google: *google_properties
    agent:
      mbus: https://mbus:mbus@0.0.0.0:6868
      ntp: *ntp
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
